language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update

install:
  - composer install --prefer-source
  - composer require --dev satooshi/php-coveralls

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
